# Generated by Django 4.2.30 on 2026-09-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='AI API Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_base_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='AI Base URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='AI 模型名称'),
        ),
    ]
