# Generated by Django 4.2.30 on 2026-09-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_ai_api_key_user_ai_base_url_user_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_authorized',
            field=models.BooleanField(default=False, verbose_name='AI 配置授权'),
        ),
    ]
