# Generated by Django 4.2.30 on 2026-09-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_system_setting_invite_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitelink',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='密保答案'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='密保问题'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
