# Generated by Django 4.2.30 on 2026-09-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_invitelink_options_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_configs',
            field=models.JSONField(blank=True, default=list, verbose_name='AI 多配置列表'),
        ),
    ]
