# Generated by Django 4.2.30 on 2026-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_ai_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='login_captcha_threshold',
            field=models.IntegerField(default=3, verbose_name='触发验证码的连续失败次数'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='login_freeze_threshold',
            field=models.IntegerField(default=10, verbose_name='触发冻结的连续失败次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_fail_count',
            field=models.IntegerField(default=0, verbose_name='连续登录失败次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_fail_count',
            field=models.IntegerField(default=0, verbose_name='连续找回密码失败次数'),
        ),
    ]
