# Generated by Django 4.2.30 on 2026-09-03 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsetting_login_captcha_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='audit_retention_days',
            field=models.IntegerField(default=90, verbose_name='审计日志保留天数（0=永久）'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='操作者账号快照')),
                ('action', models.CharField(choices=[('login', '登录'), ('login_fail', '登录失败'), ('logout', '退出登录'), ('register', '注册'), ('change_password', '修改密码'), ('delete_account', '注销账号'), ('security_question', '设置密保'), ('user_update', '编辑用户'), ('user_reset_password', '重置密码'), ('user_freeze', '冻结账号'), ('user_unfreeze', '解冻账号'), ('user_delete', '删除用户'), ('user_security', '修改用户密保'), ('security_config', '安全风控配置'), ('reg_mode', '注册模式变更'), ('invite_create', '生成邀请链接'), ('invite_delete', '删除邀请链接'), ('ai_config', 'AI 配置变更'), ('product_admin', '商品管理')], max_length=30, verbose_name='操作类型')),
                ('action_label', models.CharField(blank=True, default='', max_length=50, verbose_name='操作说明')),
                ('target_type', models.CharField(blank=True, default='', max_length=50, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, default='', max_length=20, verbose_name='目标ID')),
                ('target_name', models.CharField(blank=True, default='', max_length=150, verbose_name='目标名称')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('ip', models.CharField(blank=True, default='', max_length=64, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
