# Generated by Django 4.2.30 on 2026-09-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemsetting_audit_retention_days_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='login_lock_minutes',
            field=models.IntegerField(default=5, verbose_name='风控等待时长（分钟）'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', '登录'), ('login_fail', '登录失败'), ('logout', '退出登录'), ('register', '注册'), ('change_password', '修改密码'), ('delete_account', '注销账号'), ('security_question', '设置密保'), ('user_update', '编辑用户'), ('user_reset_password', '重置密码'), ('user_freeze', '冻结账号'), ('user_unfreeze', '解冻账号'), ('user_delete', '删除用户'), ('user_security', '修改用户密保'), ('security_config', '安全风控配置'), ('reg_mode', '注册模式变更'), ('invite_create', '生成邀请链接'), ('invite_delete', '删除邀请链接'), ('ai_config', 'AI 配置变更'), ('product_admin', '商品管理'), ('audit_delete', '删除审计日志'), ('audit_retention', '设置审计保留期限')], max_length=30, verbose_name='操作类型'),
        ),
    ]
