# Generated by Django 4.2.30 on 2026-09-07 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_locked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新会话', max_length=100, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI会话',
                'verbose_name_plural': 'AI会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('ai', 'AI')], max_length=10, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('used_config_name', models.CharField(blank=True, default='', max_length=100, verbose_name='使用的AI配置')),
                ('used_search', models.BooleanField(default=False, verbose_name='是否使用了联网搜索')),
                ('error_hint', models.TextField(blank=True, default='', verbose_name='错误提示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AI消息',
                'verbose_name_plural': 'AI消息',
                'ordering': ['created_at'],
            },
        ),
    ]
