# Generated by Django 4.2.30 on 2026-09-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chat_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='category',
            field=models.CharField(choices=[('food', '饮食'), ('clothing', '穿衣'), ('housing', '居家'), ('travel', '出行'), ('health', '健康'), ('shopping', '购物'), ('milestone', '里程碑'), ('emotion', '心理情绪'), ('exercise', '运动'), ('checkup', '产检'), ('education', '胎教')], max_length=20, verbose_name='分类'),
        ),
    ]
