# Generated by Django 4.2.30 on 2026-09-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_timelineevent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='菜品名称')),
                ('nutrient_tag', models.CharField(blank=True, max_length=100, verbose_name='营养标识')),
                ('period', models.CharField(choices=[('early', '孕早期（1-12周）'), ('mid', '孕中期（13-27周）'), ('late', '孕晚期（28-40周）')], max_length=20, verbose_name='孕期阶段')),
                ('period_month', models.CharField(default='', max_length=20, verbose_name='孕期月份分组')),
                ('ingredients', models.TextField(verbose_name='材料（支持多行）')),
                ('steps', models.TextField(verbose_name='做法步骤（支持多行）')),
                ('nutrition_tip', models.TextField(blank=True, verbose_name='营养小叮咛')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='封面图')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['period_month', 'sort_order'],
                'indexes': [models.Index(fields=['period'], name='core_recipe_period_d97f54_idx'), models.Index(fields=['period_month'], name='core_recipe_period__e6d163_idx'), models.Index(fields=['nutrient_tag'], name='core_recipe_nutrien_2175c6_idx')],
            },
        ),
    ]
