# Generated by Django 4.2.30 on 2026-09-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_recipe_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsEncyclopedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(choices=[('origin', '我从哪里来'), ('body', '我的身体'), ('growth', '我的成长'), ('mystery', '身体的奥秘')], max_length=20, verbose_name='章节')),
                ('question_number', models.IntegerField(verbose_name='问题编号')),
                ('question', models.CharField(max_length=300, verbose_name='问题')),
                ('option_a', models.CharField(max_length=300, verbose_name='选项A')),
                ('option_b', models.CharField(max_length=300, verbose_name='选项B')),
                ('option_c', models.CharField(blank=True, default='', max_length=300, verbose_name='选项C')),
                ('answer', models.TextField(verbose_name='解答正文')),
                ('comic_dialogue', models.TextField(blank=True, default='', verbose_name='漫画对话')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='配图URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['chapter', 'sort_order'],
                'indexes': [models.Index(fields=['chapter'], name='core_kidsen_chapter_822f58_idx'), models.Index(fields=['question_number'], name='core_kidsen_questio_dcb38a_idx')],
            },
        ),
    ]
