# Generated by Django 4.2.30 on 2026-09-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_kids_encyclopedia_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_token_jti',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='当前有效Token JTI'),
        ),
        migrations.CreateModel(
            name='FetalStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='故事标题')),
                ('title_en', models.CharField(blank=True, default='', max_length=400, verbose_name='英文标题')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='副标题/寓意')),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=400, verbose_name='英文副标题')),
                ('week_start', models.IntegerField(default=17, verbose_name='起始孕周')),
                ('day_offset', models.IntegerField(default=0, verbose_name='天数偏移（从week_start起第几天，0=第1天）')),
                ('day_index', models.IntegerField(default=1, verbose_name='当天序号（同一天多个故事时用）')),
                ('content', models.TextField(verbose_name='故事正文（中文）')),
                ('content_en', models.TextField(blank=True, default='', verbose_name='故事正文（英文）')),
                ('tips', models.TextField(blank=True, default='', verbose_name='胎教提示')),
                ('tips_en', models.TextField(blank=True, default='', verbose_name='英文胎教提示')),
                ('cover_image', models.URLField(blank=True, default='', max_length=500, verbose_name='封面图URL')),
                ('narrator', models.CharField(choices=[('mom', '妈妈讲'), ('dad', '爸爸讲'), ('either', '都可以')], default='mom', max_length=10, verbose_name='适合讲述者')),
                ('source', models.CharField(blank=True, default='', max_length=200, verbose_name='来源')),
                ('source_en', models.CharField(blank=True, default='', max_length=200, verbose_name='英文来源')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('view_count', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '胎教故事',
                'verbose_name_plural': '胎教故事',
                'ordering': ['week_start', 'day_offset', 'day_index'],
                'indexes': [models.Index(fields=['week_start', 'day_offset'], name='core_fetals_week_st_0a66e4_idx'), models.Index(fields=['narrator'], name='core_fetals_narrato_7ac56f_idx')],
            },
        ),
    ]
