# Generated by Django 4.2.30 on 2026-09-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_active_token_jti_fetalstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('mom', '妈妈'), ('baby', '宝宝')], max_length=10, verbose_name='物品归属')),
                ('category', models.CharField(max_length=50, verbose_name='类别')),
                ('name', models.CharField(max_length=200, verbose_name='物品名称')),
                ('quantity', models.CharField(default='1', max_length=50, verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='件', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='总价')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='示例图片')),
                ('extra_image_url', models.URLField(blank=True, null=True, verbose_name='额外示例图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '待产包参考物品',
                'verbose_name_plural': '待产包参考物品',
                'ordering': ['owner', 'sort_order', 'id'],
            },
        ),
    ]
