# Generated by Django 4.2.30 on 2026-09-09 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_baby_shopping_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='extra_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='额外示例图片'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='示例图片'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='物品归属（mom/baby）'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='provider_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_items', to='core.babyshoppingitem', verbose_name='来源参考物品'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='purchase_status',
            field=models.CharField(choices=[('not_bought', '未购买'), ('bought', '已购买'), ('considering', '考虑中')], default='not_bought', max_length=20, verbose_name='购买情况'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='总价'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.CharField(default='1', max_length=50, verbose_name='建议数量'),
        ),
    ]
