# Generated by Django 4.2.30 on 2026-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_shopping_item_expand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='手机号/用户名'),
        ),
    ]
