# Generated by Django 4.2.30 on 2026-09-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_auditlog_action_alter_auditlog_target_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='default_user_permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='普通用户默认功能与菜单权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='用户个性化权限覆盖'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ai_authorized',
            field=models.BooleanField(default=True, verbose_name='AI 配置授权'),
        ),
    ]
