# Generated by Django 4.2.30 on 2026-09-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_systemsetting_default_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='login_lock_seconds',
            field=models.IntegerField(default=300, verbose_name='风控熔断等待时长（秒）'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', '登录'), ('login_fail', '登录失败'), ('logout', '退出登录'), ('register', '注册'), ('change_password', '修改密码'), ('delete_account', '注销账号'), ('security_question', '设置密保'), ('forgot_password_attempt', '尝试找回密码'), ('forgot_password_reset', '密保找回密码'), ('forgot_password_locked', '找回密码锁定'), ('user_update', '编辑用户'), ('user_reset_password', '重置密码'), ('user_freeze', '冻结账号'), ('user_unfreeze', '解冻账号'), ('user_delete', '删除用户'), ('user_security', '修改用户密保'), ('permission_update', '修改用户权限'), ('security_config', '安全风控设置'), ('reg_mode', '注册模式切换'), ('invite_create', '创建邀请链接'), ('invite_delete', '删除邀请链接'), ('profile_update', '更新个人资料'), ('stage_update', '更新孕育阶段'), ('baby_create', '添加宝宝档案'), ('baby_update', '修改宝宝档案'), ('baby_delete', '删除宝宝档案'), ('baby_switch', '切换默认宝宝'), ('product_create', '新增商品'), ('product_update', '编辑商品'), ('product_delete', '删除商品'), ('product_import', '导入商品'), ('product_export', '导出商品'), ('product_admin', '商品管理'), ('brand_update', '更新品牌档案'), ('favorite_add', '添加收藏'), ('favorite_remove', '取消收藏'), ('health_record_create', '添加健康记录'), ('health_record_delete', '删除健康记录'), ('shopping_list_create', '创建待产清单'), ('shopping_list_generate', '智能生成清单'), ('shopping_item_update', '更新清单商品'), ('shopping_item_delete', '删除清单商品'), ('ai_chat', 'AI助手问答'), ('ai_compare', 'AI商品对比'), ('ai_evaluate', 'AI商品一键评测'), ('ai_config', 'AI配置变更'), ('ai_config_test', 'AI连接测试'), ('audit_delete', '删除审计日志'), ('audit_retention', '设置日志保留天数')], max_length=50, verbose_name='操作类型'),
        ),
    ]
