# Generated by Django 4.2.30 on 2026-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_systemsetting_login_lock_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='logo',
            field=models.TextField(blank=True, null=True, verbose_name='品牌Logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(verbose_name='主图'),
        ),
    ]
