# Generated by Django 4.2.30 on 2026-09-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_brandprofile_logo_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyprofile',
            name='is_born',
            field=models.BooleanField(default=True, verbose_name='是否已出生'),
        ),
        migrations.AlterField(
            model_name='babyprofile',
            name='birthday',
            field=models.DateField(verbose_name='出生日期/预产期'),
        ),
    ]
