# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_babyprofile_is_born_alter_babyprofile_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="admin_session_timeout_minutes",
            field=models.IntegerField(default=30, verbose_name="管理员登录无操作超时时长（分钟，0表示不超时）"),
        ),
    ]
